//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace TheSite.SchemiXSD {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class GestioneMateriali : DataSet {
        
        private TblGestioneMaterialiDataTable tableTblGestioneMateriali;
        
        public GestioneMateriali() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected GestioneMateriali(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["TblGestioneMateriali"] != null)) {
                    this.Tables.Add(new TblGestioneMaterialiDataTable(ds.Tables["TblGestioneMateriali"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public TblGestioneMaterialiDataTable TblGestioneMateriali {
            get {
                return this.tableTblGestioneMateriali;
            }
        }
        
        public override DataSet Clone() {
            GestioneMateriali cln = ((GestioneMateriali)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["TblGestioneMateriali"] != null)) {
                this.Tables.Add(new TblGestioneMaterialiDataTable(ds.Tables["TblGestioneMateriali"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableTblGestioneMateriali = ((TblGestioneMaterialiDataTable)(this.Tables["TblGestioneMateriali"]));
            if ((this.tableTblGestioneMateriali != null)) {
                this.tableTblGestioneMateriali.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "GestioneMateriali";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/GestioneMateriali.xsd";
            this.Locale = new System.Globalization.CultureInfo("it-IT");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableTblGestioneMateriali = new TblGestioneMaterialiDataTable();
            this.Tables.Add(this.tableTblGestioneMateriali);
        }
        
        private bool ShouldSerializeTblGestioneMateriali() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void TblGestioneMaterialiRowChangeEventHandler(object sender, TblGestioneMaterialiRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class TblGestioneMaterialiDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnID;
            
            private DataColumn columnWR_ID;
            
            private DataColumn columnID_MATERIALE;
            
            private DataColumn columnDESCRIZIONE;
            
            private DataColumn columnPREZZO_UNITARIO;
            
            private DataColumn columnQUANTITA;
            
            private DataColumn columnTOTALE;
            
            private DataColumn columnTOTALEENTRATA;
            
            private DataColumn columnTOTALEUSCITA;
            
            private DataColumn columnQUANTITAENTRATA;
            
            private DataColumn columnQUANTITAUSCITA;
            
            private DataColumn columnDATA_INSERIMENTO;
            
            internal TblGestioneMaterialiDataTable() : 
                    base("TblGestioneMateriali") {
                this.InitClass();
            }
            
            internal TblGestioneMaterialiDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn IDColumn {
                get {
                    return this.columnID;
                }
            }
            
            internal DataColumn WR_IDColumn {
                get {
                    return this.columnWR_ID;
                }
            }
            
            internal DataColumn ID_MATERIALEColumn {
                get {
                    return this.columnID_MATERIALE;
                }
            }
            
            internal DataColumn DESCRIZIONEColumn {
                get {
                    return this.columnDESCRIZIONE;
                }
            }
            
            internal DataColumn PREZZO_UNITARIOColumn {
                get {
                    return this.columnPREZZO_UNITARIO;
                }
            }
            
            internal DataColumn QUANTITAColumn {
                get {
                    return this.columnQUANTITA;
                }
            }
            
            internal DataColumn TOTALEColumn {
                get {
                    return this.columnTOTALE;
                }
            }
            
            internal DataColumn TOTALEENTRATAColumn {
                get {
                    return this.columnTOTALEENTRATA;
                }
            }
            
            internal DataColumn TOTALEUSCITAColumn {
                get {
                    return this.columnTOTALEUSCITA;
                }
            }
            
            internal DataColumn QUANTITAENTRATAColumn {
                get {
                    return this.columnQUANTITAENTRATA;
                }
            }
            
            internal DataColumn QUANTITAUSCITAColumn {
                get {
                    return this.columnQUANTITAUSCITA;
                }
            }
            
            internal DataColumn DATA_INSERIMENTOColumn {
                get {
                    return this.columnDATA_INSERIMENTO;
                }
            }
            
            public TblGestioneMaterialiRow this[int index] {
                get {
                    return ((TblGestioneMaterialiRow)(this.Rows[index]));
                }
            }
            
            public event TblGestioneMaterialiRowChangeEventHandler TblGestioneMaterialiRowChanged;
            
            public event TblGestioneMaterialiRowChangeEventHandler TblGestioneMaterialiRowChanging;
            
            public event TblGestioneMaterialiRowChangeEventHandler TblGestioneMaterialiRowDeleted;
            
            public event TblGestioneMaterialiRowChangeEventHandler TblGestioneMaterialiRowDeleting;
            
            public void AddTblGestioneMaterialiRow(TblGestioneMaterialiRow row) {
                this.Rows.Add(row);
            }
            
            public TblGestioneMaterialiRow AddTblGestioneMaterialiRow(System.Decimal ID, System.Decimal WR_ID, System.Decimal ID_MATERIALE, string DESCRIZIONE, System.Decimal PREZZO_UNITARIO, System.Decimal QUANTITA, System.Decimal TOTALE, System.Decimal TOTALEENTRATA, System.Decimal TOTALEUSCITA, System.Decimal QUANTITAENTRATA, System.Decimal QUANTITAUSCITA, System.DateTime DATA_INSERIMENTO) {
                TblGestioneMaterialiRow rowTblGestioneMaterialiRow = ((TblGestioneMaterialiRow)(this.NewRow()));
                rowTblGestioneMaterialiRow.ItemArray = new object[] {
                        ID,
                        WR_ID,
                        ID_MATERIALE,
                        DESCRIZIONE,
                        PREZZO_UNITARIO,
                        QUANTITA,
                        TOTALE,
                        TOTALEENTRATA,
                        TOTALEUSCITA,
                        QUANTITAENTRATA,
                        QUANTITAUSCITA,
                        DATA_INSERIMENTO};
                this.Rows.Add(rowTblGestioneMaterialiRow);
                return rowTblGestioneMaterialiRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                TblGestioneMaterialiDataTable cln = ((TblGestioneMaterialiDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new TblGestioneMaterialiDataTable();
            }
            
            internal void InitVars() {
                this.columnID = this.Columns["ID"];
                this.columnWR_ID = this.Columns["WR_ID"];
                this.columnID_MATERIALE = this.Columns["ID_MATERIALE"];
                this.columnDESCRIZIONE = this.Columns["DESCRIZIONE"];
                this.columnPREZZO_UNITARIO = this.Columns["PREZZO_UNITARIO"];
                this.columnQUANTITA = this.Columns["QUANTITA"];
                this.columnTOTALE = this.Columns["TOTALE"];
                this.columnTOTALEENTRATA = this.Columns["TOTALEENTRATA"];
                this.columnTOTALEUSCITA = this.Columns["TOTALEUSCITA"];
                this.columnQUANTITAENTRATA = this.Columns["QUANTITAENTRATA"];
                this.columnQUANTITAUSCITA = this.Columns["QUANTITAUSCITA"];
                this.columnDATA_INSERIMENTO = this.Columns["DATA_INSERIMENTO"];
            }
            
            private void InitClass() {
                this.columnID = new DataColumn("ID", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnID);
                this.columnWR_ID = new DataColumn("WR_ID", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnWR_ID);
                this.columnID_MATERIALE = new DataColumn("ID_MATERIALE", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnID_MATERIALE);
                this.columnDESCRIZIONE = new DataColumn("DESCRIZIONE", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDESCRIZIONE);
                this.columnPREZZO_UNITARIO = new DataColumn("PREZZO_UNITARIO", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPREZZO_UNITARIO);
                this.columnQUANTITA = new DataColumn("QUANTITA", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnQUANTITA);
                this.columnTOTALE = new DataColumn("TOTALE", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTOTALE);
                this.columnTOTALEENTRATA = new DataColumn("TOTALEENTRATA", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTOTALEENTRATA);
                this.columnTOTALEUSCITA = new DataColumn("TOTALEUSCITA", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTOTALEUSCITA);
                this.columnQUANTITAENTRATA = new DataColumn("QUANTITAENTRATA", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnQUANTITAENTRATA);
                this.columnQUANTITAUSCITA = new DataColumn("QUANTITAUSCITA", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnQUANTITAUSCITA);
                this.columnDATA_INSERIMENTO = new DataColumn("DATA_INSERIMENTO", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDATA_INSERIMENTO);
            }
            
            public TblGestioneMaterialiRow NewTblGestioneMaterialiRow() {
                return ((TblGestioneMaterialiRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new TblGestioneMaterialiRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(TblGestioneMaterialiRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.TblGestioneMaterialiRowChanged != null)) {
                    this.TblGestioneMaterialiRowChanged(this, new TblGestioneMaterialiRowChangeEvent(((TblGestioneMaterialiRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.TblGestioneMaterialiRowChanging != null)) {
                    this.TblGestioneMaterialiRowChanging(this, new TblGestioneMaterialiRowChangeEvent(((TblGestioneMaterialiRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.TblGestioneMaterialiRowDeleted != null)) {
                    this.TblGestioneMaterialiRowDeleted(this, new TblGestioneMaterialiRowChangeEvent(((TblGestioneMaterialiRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.TblGestioneMaterialiRowDeleting != null)) {
                    this.TblGestioneMaterialiRowDeleting(this, new TblGestioneMaterialiRowChangeEvent(((TblGestioneMaterialiRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveTblGestioneMaterialiRow(TblGestioneMaterialiRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class TblGestioneMaterialiRow : DataRow {
            
            private TblGestioneMaterialiDataTable tableTblGestioneMateriali;
            
            internal TblGestioneMaterialiRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableTblGestioneMateriali = ((TblGestioneMaterialiDataTable)(this.Table));
            }
            
            public System.Decimal ID {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTblGestioneMateriali.IDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTblGestioneMateriali.IDColumn] = value;
                }
            }
            
            public System.Decimal WR_ID {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTblGestioneMateriali.WR_IDColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTblGestioneMateriali.WR_IDColumn] = value;
                }
            }
            
            public System.Decimal ID_MATERIALE {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTblGestioneMateriali.ID_MATERIALEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTblGestioneMateriali.ID_MATERIALEColumn] = value;
                }
            }
            
            public string DESCRIZIONE {
                get {
                    try {
                        return ((string)(this[this.tableTblGestioneMateriali.DESCRIZIONEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTblGestioneMateriali.DESCRIZIONEColumn] = value;
                }
            }
            
            public System.Decimal PREZZO_UNITARIO {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTblGestioneMateriali.PREZZO_UNITARIOColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTblGestioneMateriali.PREZZO_UNITARIOColumn] = value;
                }
            }
            
            public System.Decimal QUANTITA {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTblGestioneMateriali.QUANTITAColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTblGestioneMateriali.QUANTITAColumn] = value;
                }
            }
            
            public System.Decimal TOTALE {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTblGestioneMateriali.TOTALEColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTblGestioneMateriali.TOTALEColumn] = value;
                }
            }
            
            public System.Decimal TOTALEENTRATA {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTblGestioneMateriali.TOTALEENTRATAColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTblGestioneMateriali.TOTALEENTRATAColumn] = value;
                }
            }
            
            public System.Decimal TOTALEUSCITA {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTblGestioneMateriali.TOTALEUSCITAColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTblGestioneMateriali.TOTALEUSCITAColumn] = value;
                }
            }
            
            public System.Decimal QUANTITAENTRATA {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTblGestioneMateriali.QUANTITAENTRATAColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTblGestioneMateriali.QUANTITAENTRATAColumn] = value;
                }
            }
            
            public System.Decimal QUANTITAUSCITA {
                get {
                    try {
                        return ((System.Decimal)(this[this.tableTblGestioneMateriali.QUANTITAUSCITAColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTblGestioneMateriali.QUANTITAUSCITAColumn] = value;
                }
            }
            
            public System.DateTime DATA_INSERIMENTO {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableTblGestioneMateriali.DATA_INSERIMENTOColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableTblGestioneMateriali.DATA_INSERIMENTOColumn] = value;
                }
            }
            
            public bool IsIDNull() {
                return this.IsNull(this.tableTblGestioneMateriali.IDColumn);
            }
            
            public void SetIDNull() {
                this[this.tableTblGestioneMateriali.IDColumn] = System.Convert.DBNull;
            }
            
            public bool IsWR_IDNull() {
                return this.IsNull(this.tableTblGestioneMateriali.WR_IDColumn);
            }
            
            public void SetWR_IDNull() {
                this[this.tableTblGestioneMateriali.WR_IDColumn] = System.Convert.DBNull;
            }
            
            public bool IsID_MATERIALENull() {
                return this.IsNull(this.tableTblGestioneMateriali.ID_MATERIALEColumn);
            }
            
            public void SetID_MATERIALENull() {
                this[this.tableTblGestioneMateriali.ID_MATERIALEColumn] = System.Convert.DBNull;
            }
            
            public bool IsDESCRIZIONENull() {
                return this.IsNull(this.tableTblGestioneMateriali.DESCRIZIONEColumn);
            }
            
            public void SetDESCRIZIONENull() {
                this[this.tableTblGestioneMateriali.DESCRIZIONEColumn] = System.Convert.DBNull;
            }
            
            public bool IsPREZZO_UNITARIONull() {
                return this.IsNull(this.tableTblGestioneMateriali.PREZZO_UNITARIOColumn);
            }
            
            public void SetPREZZO_UNITARIONull() {
                this[this.tableTblGestioneMateriali.PREZZO_UNITARIOColumn] = System.Convert.DBNull;
            }
            
            public bool IsQUANTITANull() {
                return this.IsNull(this.tableTblGestioneMateriali.QUANTITAColumn);
            }
            
            public void SetQUANTITANull() {
                this[this.tableTblGestioneMateriali.QUANTITAColumn] = System.Convert.DBNull;
            }
            
            public bool IsTOTALENull() {
                return this.IsNull(this.tableTblGestioneMateriali.TOTALEColumn);
            }
            
            public void SetTOTALENull() {
                this[this.tableTblGestioneMateriali.TOTALEColumn] = System.Convert.DBNull;
            }
            
            public bool IsTOTALEENTRATANull() {
                return this.IsNull(this.tableTblGestioneMateriali.TOTALEENTRATAColumn);
            }
            
            public void SetTOTALEENTRATANull() {
                this[this.tableTblGestioneMateriali.TOTALEENTRATAColumn] = System.Convert.DBNull;
            }
            
            public bool IsTOTALEUSCITANull() {
                return this.IsNull(this.tableTblGestioneMateriali.TOTALEUSCITAColumn);
            }
            
            public void SetTOTALEUSCITANull() {
                this[this.tableTblGestioneMateriali.TOTALEUSCITAColumn] = System.Convert.DBNull;
            }
            
            public bool IsQUANTITAENTRATANull() {
                return this.IsNull(this.tableTblGestioneMateriali.QUANTITAENTRATAColumn);
            }
            
            public void SetQUANTITAENTRATANull() {
                this[this.tableTblGestioneMateriali.QUANTITAENTRATAColumn] = System.Convert.DBNull;
            }
            
            public bool IsQUANTITAUSCITANull() {
                return this.IsNull(this.tableTblGestioneMateriali.QUANTITAUSCITAColumn);
            }
            
            public void SetQUANTITAUSCITANull() {
                this[this.tableTblGestioneMateriali.QUANTITAUSCITAColumn] = System.Convert.DBNull;
            }
            
            public bool IsDATA_INSERIMENTONull() {
                return this.IsNull(this.tableTblGestioneMateriali.DATA_INSERIMENTOColumn);
            }
            
            public void SetDATA_INSERIMENTONull() {
                this[this.tableTblGestioneMateriali.DATA_INSERIMENTOColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class TblGestioneMaterialiRowChangeEvent : EventArgs {
            
            private TblGestioneMaterialiRow eventRow;
            
            private DataRowAction eventAction;
            
            public TblGestioneMaterialiRowChangeEvent(TblGestioneMaterialiRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public TblGestioneMaterialiRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
